require :
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Rails/FilePath:
  Enabled: false

